export default [
  {
    title: "The Beginning",
    desc: "Pada minggu pertama, Anda telah mengambil langkah pertama yang berani menuju transformasi diri. Keputusan untuk mengatasi tantangan PMO adalah langkah penting yang menunjukkan tekad dan keinginan untuk hidup lebih baik. Jadikan waktu ini sebagai fondasi kuat untuk perjalanan Anda.",
    days_desc: [
      "Hari ini adalah awal dari perjalanan menuju kehidupan yang lebih baik. Anda telah mengambil langkah pertama yang penuh tekad. Jadikan hari ini sebagai tonggak untuk mengubah arah hidup Anda.",
      "Terus berpegang pada tekad Anda. Setiap langkah kecil sangat berarti dalam perubahan besar yang Anda raih. Perhatikan keberanian yang Anda tunjukkan sejauh ini.",
      "Anda melangkah maju dengan tekad kuat. Ingatlah bahwa setiap langkah yang Anda ambil saat ini adalah investasi untuk masa depan yang lebih baik.",
      "Meskipun tantangan mungkin muncul, Anda telah membuktikan kemauan dan semangat Anda. Jika pernah merasa lelah, ingatlah mengapa Anda memulai ini.",
      "Pada titik ini, Anda sudah melalui setengah minggu dan berada di jalur yang benar. Ingatlah mengapa Anda memutuskan untuk mengubah diri Anda dan teruslah bergerak maju.",
      "Anda telah menciptakan awal yang kuat. Berbicaralah dengan diri Anda sendiri dengan penuh kasih dan ketenangan, karena Anda layak mendapatkan perubahan positif yang sedang Anda lakukan.",
      "Minggu pertama telah berlalu dengan sukses. Perjalanan ini mungkin baru dimulai, tetapi Anda telah membuktikan bahwa Anda memiliki tekad untuk menghadapinya. Teruslah melangkah maju dengan percaya diri.",
    ],
  },
  {
    title: "Self Control",
    desc: "Di minggu kedua, Anda memulai perjalanan menguji dan membangun kendali diri. Ini adalah waktu untuk mengenali dan menantang godaan pertama yang mungkin muncul. Ingatlah bahwa Anda memiliki kekuatan untuk mengubah kebiasaan lama menjadi yang lebih sehat dan produktif.",
    days_desc: [
      "Hari ini adalah awal dari perjalanan menuju kehidupan yang lebih baik. Anda telah mengambil langkah pertama yang penuh tekad. Jadikan hari ini sebagai tonggak untuk mengubah arah hidup Anda.",
      "Anda berada dalam perjalanan untuk menjadi penguasa atas diri sendiri. Pikirkan tentang potensi luar biasa yang dapat Anda capai dengan mengendalikan naluri dan dorongan Anda.",
      "Teruslah merayakan setiap kemenangan kecil dalam mengatasi godaan. Anda membangun momentum positif dan semakin dekat dengan tujuan Anda.",
      "Anda telah memberi bukti bahwa Anda memiliki kekuatan untuk mengubah arah hidup Anda. Setiap kali Anda menghadapi godaan dan berhasil mengatasi, Anda semakin kuat.",
      "Di minggu ini, Anda belajar untuk menemukan kekuatan dalam diri sendiri. Anda adalah pahlawan dalam cerita ini, mengatasi hambatan dan tumbuh lebih kuat.",
      "Tantangan adalah bagian dari perjalanan ini. Saat Anda melawan godaan, ingatlah bahwa Anda sedang membangun karakter dan ketangguhan yang luar biasa.",
      "Minggu kedua telah berakhir, dan Anda terus bertahan. Tantangan ini tidak mudah, tetapi Anda terus membuktikan bahwa Anda memiliki kemauan yang tak tergoyahkan.",
    ],
  },
  {
    title: "Gaining Momentum",
    desc: "Minggu ketiga adalah saat Anda mulai merasakan momentum yang meningkat. Perlahan namun pasti, Anda merasakan bahwa perubahan positif sedang terjadi dalam hidup Anda. Tetap fokus pada tujuan Anda dan gunakan energi ini untuk memperkuat komitmen Anda.",
    days_desc: [
      "Momentum positif semakin terasa. Pikirkan tentang tujuan yang ingin Anda capai dan biarkan semangat ini memandu Anda.",
      "Anda sedang membangun kembali hidup Anda. Setiap langkah kecil yang Anda ambil saat ini berkontribusi pada perubahan besar yang akan datang.",
      "Pikirkan tentang perubahan positif yang Anda lihat pada diri Anda sendiri. Jangan lupa merayakan pencapaian-pencapaian ini.",
      "Ingatlah bahwa perjalanan ini adalah tentang perlahan namun pasti. Tetap fokus pada tujuan Anda dan jangan biarkan hal-hal kecil menggoyahkan semangat Anda.",
      "Energi positif yang semakin meningkat adalah tanda-tanda perubahan positif dalam diri Anda. Teruslah memotivasi diri sendiri dan jadikan ini sebagai saat untuk bergerak lebih maju.",
      "Setiap langkah yang Anda ambil saat ini adalah investasi dalam kesejahteraan masa depan Anda. Lihatlah ke belakang dan lihatlah betapa jauhnya Anda telah datang.",
      "Anda telah mengatasi tiga minggu pertama dengan tekad yang luar biasa. Melihat seberapa jauh Anda telah maju dapat menjadi inspirasi untuk terus mengejar tujuan Anda.",
    ],
  },
  {
    title: "The Flatline",
    desc: 'Pada minggu keempat, Anda mungkin mengalami apa yang disebut sebagai "flatline", di mana hasrat dan energi seksual mungkin tampak berkurang. Ini adalah tahap normal dalam proses pemulihan. Lihatlah ini sebagai kesempatan untuk mendalami pemahaman tentang diri Anda dan mengeksplorasi hal-hal baru.',
    days_desc: [
      "Pada minggu keempat, Anda mungkin merasakan perubahan energi dan dorongan. Ini adalah tahap normal dalam pemulihan. Lihatlah ini sebagai kesempatan untuk memahami diri Anda lebih dalam.",
      "Ketika energi seksual Anda mungkin berkurang, ingatlah bahwa ini adalah bagian dari perjalanan Anda. Gunakan waktu ini untuk mengeksplorasi minat dan kegiatan baru.",
      'Anda sedang melewati tahap "flatline" dengan keberanian. Saat perasaan berubah, tahanlah dan percayalah bahwa energi akan kembali.',
      "Ingatlah bahwa Anda tidak sendirian dalam menghadapi tantangan ini. Bergabunglah dengan kelompok dukungan atau berbicaralah dengan seseorang yang Anda percayai.",
      'Mengatasi tahap "flatline" menunjukkan ketahanan mental Anda. Ini adalah kesempatan untuk menunjukkan kepada diri sendiri bahwa Anda bisa menghadapi perubahan ini.',
      "Saat Anda melalui minggu ini, ingatlah tentang niat baik yang mendorong Anda memulai perubahan ini. Jangan ragu untuk mencari dukungan dari orang-orang di sekitar Anda.",
      "Minggu keempat telah berakhir. Anda telah menghadapi tantangan dengan tekad dan keberanian. Terus bergerak maju dengan percaya diri karena perubahan positif sedang terjadi.",
    ],
  },
  {
    title: "The Flatline 2",
    desc: 'Minggu kelima menandai kelanjutan dari tahap "flatline." Meskipun tantangan mungkin ada, ingatlah bahwa ini adalah bagian dari perjalanan pemulihan Anda. Tetaplah kuat dan fokus pada perkembangan yang telah Anda capai sejauh ini.',
    days_desc: [
      'Di minggu kelima ini, Anda mungkin masih merasakan pengaruh dari tahap "flatline." Ingatlah bahwa ini adalah bagian normal dari perjalanan pemulihan Anda. Teruslah melangkah maju dengan tekad yang tak tergoyahkan.',
      "Anda sedang melalui tahap yang memerlukan kesabaran dan ketekunan. Perjalanan ini adalah tentang mengatasi setiap tantangan yang muncul di depan Anda.",
      "Teruslah berfokus pada tujuan Anda meskipun mungkin ada ketidaknyamanan. Ingatlah bahwa Anda sedang membangun kekuatan yang lebih besar melalui kesulitan ini.",
      "Lihatlah kembali pada perubahan positif yang telah Anda alami selama perjalanan ini. Ini adalah bukti bahwa Anda sedang membuat kemajuan meskipun mungkin ada saat-saat yang sulit.",
      "Jika Anda merasa frustrasi atau lelah, ingatlah bahwa ini hanya tahap sementara. Anda memiliki kapasitas untuk terus maju meskipun tantangan-tantangan ini.",
      "Tantangan ini membantu Anda berkembang lebih kuat. Teruslah berlatih kesabaran dan penerimaan terhadap diri sendiri saat Anda melalui tahap ini.",
      "Minggu kelima telah berlalu, dan Anda masih melangkah maju. Meskipun tantangan mungkin ada, tekad Anda adalah sumber kekuatan yang tak tergoyahkan.",
    ],
  },
  {
    title: "The Flatline 3",
    desc: 'Di minggu keenam, Anda mungkin masih merasakan pengaruh tahap "flatline." Ingatlah bahwa perjalanan pemulihan memiliki puncak dan lembah, dan saat Anda melanjutkan, energi dan semangat akan pulih. Tetap konsisten dalam upaya Anda.',
    days_desc: [
      'Pada minggu keenam ini, Anda mungkin masih menghadapi pengaruh dari tahap "flatline." Ingatlah bahwa ini adalah bagian dari perjalanan pemulihan Anda dan setiap tahap memiliki tujuan dan manfaatnya.',
      "Teruslah menghadapi tantangan dengan tekad yang kuat. Meskipun Anda mungkin merasa datar saat ini, jangan biarkan itu menghalangi semangat Anda.",
      "Pergunakan waktu ini untuk merenung dan memahami diri Anda lebih dalam. Apa yang Anda pelajari tentang diri Anda selama tahap-tahap ini?",
      "Anda telah melewati beberapa minggu yang menguji ketahanan Anda. Tetap fokus pada niat baik Anda dan teruslah bergerak maju.",
      "Setiap tahap adalah bagian penting dari perjalanan ini. Anda mengatasi tantangan dengan penuh tekad dan ini adalah bukti bahwa Anda mampu.",
      "Teruslah mencari dukungan dari orang-orang yang mendukung perubahan Anda. Berbicaralah tentang perasaan Anda dan bagaimana Anda dapat mengatasi tantangan ini.",
      'Minggu keenam telah berakhir. Meskipun Anda mungkin masih merasakan pengaruh tahap "flatline," jangan lupa betapa besarnya pencapaian Anda selama perjalanan ini.',
    ],
  },
  {
    title: "The Recovery",
    desc: "Minggu ketujuh adalah saat pemulihan Anda semakin jelas terlihat. Anda mulai merasakan manfaat dari perubahan yang Anda buat. Jika Anda pernah merasa lelah atau ragu, ingatlah mengapa Anda memulai tantangan ini dan teruslah maju.",
    days_desc: [
      "Pada minggu ketujuh ini, Anda mulai melihat pemulihan yang semakin jelas. Anda merasakan manfaat dari perubahan yang Anda lakukan dan itu adalah hasil nyata dari upaya Anda.",
      "Ini adalah waktu untuk merayakan pencapaian-pencapaian Anda. Jangan lupakan perjuangan Anda dan betapa jauhnya Anda telah datang.",
      "Saat Anda melalui minggu ini, ingatlah mengapa Anda memulai tantangan ini. Anda telah membuktikan kepada diri sendiri bahwa Anda mampu melakukan perubahan yang positif.",
      "Teruslah merasakan efek positif dari perubahan yang Anda lakukan. Jadikan ini sebagai motivasi untuk tetap berkomitmen pada tujuan Anda.",
      "Melihat hasil nyata dari upaya Anda membuat setiap perjuangan berharga. Tetaplah fokus pada perubahan positif yang Anda lihat dalam diri Anda.",
      "Anda telah berjuang keras selama beberapa minggu dan Anda semakin mendekati tujuan Anda. Jadikan waktu ini untuk merenungkan perjalanan Anda dan bagaimana Anda ingin melanjutkannya.",
      "Minggu ketujuh telah berakhir, dan Anda semakin dekat dengan keberhasilan. Ingatlah bahwa setiap langkah kecil adalah bagian dari perubahan besar yang sedang Anda ciptakan.",
    ],
  },
  {
    title: "The Optimism And Energy",
    desc: "Pada minggu kedelapan, optimisme dan energi positif mulai mengalir kembali. Anda melihat lebih banyak perubahan positif dalam pikiran, tubuh, dan emosi Anda. Rasakan kebanggaan atas pencapaian Anda dan gunakan energi ini untuk terus meningkatkan diri.",
    days_desc: [
      "Pada minggu kedelapan ini, Anda merasakan optimisme dan energi positif yang semakin kuat. Anda melihat lebih banyak perubahan positif dalam pikiran, tubuh, dan emosi Anda.",
      "Teruslah berfokus pada hal-hal yang membuat Anda merasa positif. Dalam situasi apa pun, carilah sisi terang dan pelajaran positif.",
      "Anda adalah agen perubahan dalam hidup Anda sendiri. Percayalah pada diri Anda dan pada kemampuan Anda untuk terus tumbuh dan berkembang.",
      "Gunakan energi positif ini untuk menjalani hari dengan semangat. Anda telah bekerja keras dan sekarang Anda mulai melihat buah-buah dari usaha Anda.",
      "Jangan ragu untuk membagikan kebahagiaan Anda dengan orang-orang di sekitar Anda. Semangat Anda dapat menginspirasi orang lain untuk mencapai tujuan mereka sendiri.",
      "Ingatlah bahwa Anda memiliki kekuatan untuk mempengaruhi pikiran dan emosi Anda. Teruslah berlatih positivitas dalam setiap aspek kehidupan Anda.",
      "Minggu kedelapan telah berakhir. Anda telah mengatasi banyak tantangan dan saat ini adalah bukti bahwa Anda mampu menciptakan perubahan positif dalam hidup Anda.",
    ],
  },
  {
    title: "Ongoing To Alpha",
    desc: "Di minggu kesembilan, Anda melangkah lebih dekat menuju versi terbaik dari diri Anda. Anda mengasah ketangguhan mental dan semangat untuk terus maju. Teruslah mengatasi rintangan yang mungkin muncul dengan kepercayaan diri.",
    days_desc: [
      "Di minggu kesembilan ini, Anda melangkah lebih dekat menuju versi terbaik dari diri Anda. Anda mengasah ketangguhan mental dan semangat untuk terus maju.",
      "Jangan lupa menghargai perjalanan Anda. Setiap langkah yang Anda ambil adalah langkah ke arah kehidupan yang lebih baik.",
      "Teruslah mengasah kemampuan Anda untuk mengatasi rintangan. Anda telah melewati begitu banyak hambatan dan Anda terus berkembang.",
      "Perjalanan ini adalah tentang menghadapi perubahan dengan kepala tegak. Terus berpegang pada tekad Anda dan jadikan setiap hari sebagai peluang untuk tumbuh.",
      "Anda mungkin merasa lebih kuat dan lebih berdaya saat Anda melanjutkan minggu ini. Jadikan setiap tantangan sebagai peluang untuk menguji diri Anda.",
      "Tetaplah menjaga semangat Anda meskipun mungkin ada rintangan. Anda telah menunjukkan ketangguhan Anda selama berbulan-bulan ini.",
      "Minggu kesembilan telah berakhir dan Anda terus berjuang. Anda adalah contoh nyata dari kemauan yang kuat dan tekad yang tak tergoyahkan.",
    ],
  },
  {
    title: "The Alpha",
    desc: "Minggu kesepuluh adalah puncak pencapaian. Anda telah melalui perjalanan mengubah hidup dan melihat hasil nyata dari usaha Anda. Anda mungkin merasa lebih percaya diri, lebih kuat, dan lebih bersemangat dalam menjalani kehidupan. Tetapkan fondasi yang telah Anda bangun untuk masa depan yang cerah.",
    days_desc: [
      "Pada minggu kesepuluh ini, Anda mencapai puncak pencapaian. Anda telah melalui perjalanan mengubah hidup dan melihat hasil nyata dari usaha Anda.",
      'Anda telah mencapai status "Alpha" dalam perjalanan Anda. Anda merasa lebih percaya diri, lebih kuat, dan lebih bersemangat dalam menjalani kehidupan.',
      "Jadikan setiap langkah yang Anda ambil saat ini sebagai puncak perubahan yang Anda raih. Anda adalah contoh nyata bahwa ketekunan dan komitmen membawa hasil yang luar biasa.",
      "Teruslah memanfaatkan momentum positif Anda. Anda telah melalui banyak tantangan dan saat ini adalah bukti nyata bahwa Anda dapat mencapai apa pun yang Anda tetapkan.",
      "Mengingat perjalanan Anda selama 10 minggu terakhir, rasakan kebanggaan dalam setiap pencapaian Anda. Anda telah membuktikan kepada diri sendiri seberapa kuatnya Anda.",
      "Lihatlah ke masa depan dengan keyakinan. Anda telah menciptakan dasar yang kokoh untuk kehidupan yang lebih baik dan lebih seimbang.",
      "Minggu kesepuluh dan perjalanan Anda telah berakhir. Anda melihat hasil perjuangan Anda dalam segala kejayaan dan tantangan. Jadikan masa depan sebagai peluang untuk terus tumbuh dan berkembang.",
    ],
  },
];
